---

- name: Remove ntp
  become: yes
  package:
    name: ntp
    state: absent
    purge: true
  tags:
    - ntp

- name: Set timezone
  become: yes
  timezone:
    name: "{{ ntp_timezone }}"
  tags:
    - ntp

- name: Create config file
  become: yes
  template:
    src: templates/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
  tags:
    - ntp

- name: Check if ntp is enabled
  become: yes
  command: timedatectl
  register: time_info
  changed_when: false

- name: Enable timedatectl ntp
  become: yes
  command: timedatectl set-ntp true
  when: "ntp and time_info.stdout.find('Network time on: yes') == -1"
  notify: restart timedatectl
  tags:
    - ntp